title: MoneyBay Blog
description: >-
  MoneyBay - Ứng dụng quản lý chi tiêu cá nhân thông minh, giúp bạn kiểm soát tài chính hiệu quả.
  Blog chia sẻ kiến thức về quản lý tài chính cá nhân.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moneybay.app" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: moneybayapp #if your site has a twitter account, enter it here

# Author Settings
author: MoneyBay Team # add your name
author-img: avatar_01.png # add your photo
about-author: Chúng tôi là đội ngũ phát triển MoneyBay - ứng dụng quản lý tài chính cá nhân thông minh. # add description
social-twitter: moneybayapp # add your Twitter handle
social-facebook: moneybayapp # add your Facebook handle
social-github: moneybayapp # add your Github handle
social-linkedin: moneybayapp # add your Linkedin handle
social-email: support@moneybay.app # add your Email address

# Disqus
discus-identifier: moneybay-blog # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "blog/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]