title: MoneyBay
email: support@moneybay.app
description: >-
  MoneyBay - Ứng dụng quản lý chi tiêu cá nhân thông minh, giúp bạn kiểm soát tài chính hiệu quả.
baseurl: "" # the subpath of your site
url: "https://moneybay.app" # the base hostname & protocol for your site
twitter_username: moneybayapp
github_username:  qrbayapp

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 