title: My Website
email: your-email@example.com
description: >-
  Write an awesome description for your new site here.
baseurl: "" # the subpath of your site
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 